version: "3"

services:
  dev-vidhanam:
    container_name: DevVidhaanamContainer
    build: .
    image: devvidhaanam:v1
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
